services:
  - type: web
    name: codeprac-backend
    env: python
    plan: starter
    pythonVersion: 3.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9"
      - key: PORT
        value: "5000"
